package pokemon_online.world_builder;


import java.awt.Window;

import pokemon_online.land.Land;

public class AnteprimaLand extends javax.swing.JDialog {
    
    /** Creates new form AnteprimaLand */
    public AnteprimaLand(java.awt.Frame parent, boolean modal, Land land, Window formChiamante) {
        super(parent, modal);
        initComponents();
        this.pannelloAnteprimaLand.setLand(land);
        this.land = land;
        this.settaBarreScorrimento();
        this.setModal(true);
        this.centraFrameSuFrame(formChiamante);
        setVisible(true);
        repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pannelloAnteprimaLand = new PannelloAnteprimaLand();
        jCheckBoxGriglia = new javax.swing.JCheckBox();
        jScrollBarVert = new javax.swing.JScrollBar();
        jScrollBarOriz = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anteprima");
        setResizable(false);
        pannelloAnteprimaLand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pannelloAnteprimaLand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloAnteprimaLandMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloAnteprimaLandLayout = new org.jdesktop.layout.GroupLayout(pannelloAnteprimaLand);
        pannelloAnteprimaLand.setLayout(pannelloAnteprimaLandLayout);
        pannelloAnteprimaLandLayout.setHorizontalGroup(
            pannelloAnteprimaLandLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 353, Short.MAX_VALUE)
        );
        pannelloAnteprimaLandLayout.setVerticalGroup(
            pannelloAnteprimaLandLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 225, Short.MAX_VALUE)
        );

        jCheckBoxGriglia.setText("Griglia");
        jCheckBoxGriglia.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxGriglia.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxGriglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGrigliaActionPerformed(evt);
            }
        });

        jScrollBarVert.setEnabled(false);
        jScrollBarVert.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarVertAdjustmentValueChanged(evt);
            }
        });

        jScrollBarOriz.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBarOriz.setEnabled(false);
        jScrollBarOriz.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarOrizAdjustmentValueChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBoxGriglia)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollBarOriz, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .add(pannelloAnteprimaLand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollBarVert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jCheckBoxGriglia)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollBarVert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pannelloAnteprimaLand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollBarOriz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pannelloAnteprimaLandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloAnteprimaLandMouseClicked
        int colonna = this.setClick(evt.getX() + this.pannelloAnteprimaLand.getXScroll());
        int riga = this.setClick(evt.getY() + this.pannelloAnteprimaLand.getYScroll());
        if ((colonna < this.land.getColsCount())&&(riga < this.land.getRowsCount()))
            if (this.land.componenti[colonna][riga] != null){
                new AttributiComponente(new javax.swing.JFrame(), true, this.land.componenti[colonna][riga], this);
                this.pannelloAnteprimaLand.setLand(this.land);
            }
        repaint();
    }//GEN-LAST:event_pannelloAnteprimaLandMouseClicked

    private void jScrollBarOrizAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarOrizAdjustmentValueChanged
        this.pannelloAnteprimaLand.setXScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarOrizAdjustmentValueChanged

    private void jScrollBarVertAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarVertAdjustmentValueChanged
        this.pannelloAnteprimaLand.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarVertAdjustmentValueChanged

    private void jCheckBoxGrigliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGrigliaActionPerformed
        if (this.jCheckBoxGriglia.isSelected() == true)
            this.pannelloAnteprimaLand.setGriglia(true);
        else
            this.pannelloAnteprimaLand.setGriglia(false);
        repaint();
    }//GEN-LAST:event_jCheckBoxGrigliaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxGriglia;
    private javax.swing.JScrollBar jScrollBarOriz;
    private javax.swing.JScrollBar jScrollBarVert;
    private PannelloAnteprimaLand pannelloAnteprimaLand;
    // End of variables declaration//GEN-END:variables
    Land land;
    
    void centraFrameSuFrame(Window frame2) { //Posiziona il frame corrente al centro di frame2
        int x = frame2.getX();
        int y = frame2.getY();
        int larghezza = frame2.getWidth();
        int altezza = frame2.getHeight();
        this.setLocation((x + larghezza / 2) - this.getWidth()/2, (y + altezza / 2) - this.getHeight() / 2);
    }
    
    void settaBarreScorrimento(){
            //Setto la barra a scorrimento orizzontale
            if (this.land.getColsCount() * 16 > this.pannelloAnteprimaLand.getWidth()){
                this.jScrollBarOriz.setEnabled(true);
                this.jScrollBarOriz.setMaximum((this.land.getColsCount() * 16 - this.pannelloAnteprimaLand.getWidth()) + 16);
            }
            //Setto la barra a scorrimento verticale
            if (this.land.getRowsCount() * 16 > this.pannelloAnteprimaLand.getHeight()){
                this.jScrollBarVert.setEnabled(true);
                this.jScrollBarVert.setMaximum((this.land.getRowsCount() * 16 - this.pannelloAnteprimaLand.getHeight()) + 16);
            }
    }
    
    int setClick(int coordinata){
        //CICLO
        int trovato = 0;
        while (trovato == 0) {
            if (coordinata % 16 == 0) //Se la coordinata è un multiplo di 32
                trovato = 1;
        else //Se la coordinata non è un multiplo di 32
            coordinata--;
        }
        return coordinata/16;
    }
}
