package pokemon_online.world_builder;

import java.awt.Window;
import java.awt.Dimension;

public class AttributiComponente extends javax.swing.JDialog {

	/** Creates new form AttributiComponente */
	public AttributiComponente(java.awt.Frame parent, boolean modal, Componente componente, Window formChiamante) {
		super(parent, modal);
		initComponents();
		this.componente = componente;
		this.inizializzaComponenti();
		this.centraFrameSuFrame(formChiamante);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabelLand = new javax.swing.JLabel();
		jButtonModifica = new javax.swing.JButton();
		jTextFieldLandArrivo = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBoxTipo = new javax.swing.JComboBox();
		jTextFieldNome = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabelTesto = new javax.swing.JLabel();
		jTextFieldTesto = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabelPrezzo = new javax.swing.JLabel();
		jTextFieldPrezzo = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabelLand.setText("Land arrivo:");
		jLabelLand.setEnabled(false);

		jButtonModifica.setText("modifica");
		jButtonModifica.setEnabled(false);
		jButtonModifica.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonModificaActionPerformed(evt);
			}
		});

		jTextFieldLandArrivo.setEditable(false);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup().addContainerGap().add(jLabelLand)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jTextFieldLandArrivo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButtonModifica)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup().addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabelLand)
								.add(jButtonModifica).add(jTextFieldLandArrivo,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabel1.setText("Nome:");

		jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Terreno", "Blocco", "Porta", "Cartello", "Zona d'erba", "Blocco Rim", "Check Point" }));
		jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxTipoActionPerformed(evt);
			}
		});

		jTextFieldNome.setEditable(false);

		jLabel2.setText("Tipo:");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup().addContainerGap()
						.add(jPanel2Layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jLabel1).add(jLabel2))
						.add(15, 15, 15)
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jTextFieldNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
								.add(jComboBoxTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup().addContainerGap()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel1)
								.add(jTextFieldNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2)
								.add(jComboBoxTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabelTesto.setText("Testo:");
		jLabelTesto.setEnabled(false);

		jTextFieldTesto.setEnabled(false);

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel3Layout.createSequentialGroup().addContainerGap().add(jLabelTesto)
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jTextFieldTesto,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel3Layout.createSequentialGroup().addContainerGap()
						.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabelTesto).add(jTextFieldTesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabelPrezzo.setText("Prezzo:");
		jLabelPrezzo.setEnabled(false);

		jTextFieldPrezzo.setEnabled(false);

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel4Layout.createSequentialGroup().addContainerGap().add(jLabelPrezzo)
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jTextFieldPrezzo,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel4Layout.createSequentialGroup().addContainerGap()
						.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabelPrezzo).add(jTextFieldPrezzo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup().addContainerGap()
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout
				.createSequentialGroup().addContainerGap()
				.add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
				.add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
				.add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButton1).addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonModificaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonModificaActionPerformed
		SetPorta setPorta = new SetPorta(new javax.swing.JFrame(), true, this.componente, this);
		this.jTextFieldLandArrivo.setText(this.componente.landArrivo);
		repaint();
	}// GEN-LAST:event_jButtonModificaActionPerformed

	private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxTipoActionPerformed
		switch (this.jComboBoxTipo.getSelectedIndex()) {
		case 2:
			this.jLabelLand.setEnabled(true);
			this.jButtonModifica.setEnabled(true);
			this.jLabelTesto.setEnabled(false);
			this.jTextFieldTesto.setEnabled(false);
			this.jLabelPrezzo.setEnabled(false);
			this.jTextFieldPrezzo.setEnabled(false);
			break;
		case 3:
			this.jLabelTesto.setEnabled(true);
			this.jTextFieldTesto.setEnabled(true);
			this.jLabelLand.setEnabled(false);
			this.jButtonModifica.setEnabled(false);
			this.jLabelPrezzo.setEnabled(false);
			this.jTextFieldPrezzo.setEnabled(false);
			break;
		case 6:
			this.jLabelPrezzo.setEnabled(true);
			this.jTextFieldPrezzo.setEnabled(true);
			this.jLabelLand.setEnabled(false);
			this.jButtonModifica.setEnabled(false);
			this.jLabelTesto.setEnabled(false);
			this.jTextFieldTesto.setEnabled(false);
			break;
		default:
			this.jLabelTesto.setEnabled(false);
			this.jTextFieldTesto.setEnabled(false);
			this.jLabelLand.setEnabled(false);
			this.jButtonModifica.setEnabled(false);
			this.jLabelPrezzo.setEnabled(false);
			this.jTextFieldPrezzo.setEnabled(false);
			break;
		}
		repaint();
	}// GEN-LAST:event_jComboBoxTipoActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
//		TODO this.componente.tipo = this.jComboBoxTipo.getSelectedIndex();
		if ((this.jTextFieldTesto.getText().isEmpty() == false) && (this.jComboBoxTipo.getSelectedIndex() == 3))
			this.componente.testo = this.jTextFieldTesto.getText();
		if ((this.jTextFieldLandArrivo.getText().isEmpty() == false) && (this.jComboBoxTipo.getSelectedIndex() == 2))
			this.componente.testo = this.jTextFieldTesto.getText();
		if ((this.jTextFieldPrezzo.getText().isEmpty() == false) && (this.jComboBoxTipo.getSelectedIndex() == 6))
			this.componente.prezzo = Integer.parseInt(this.jTextFieldPrezzo.getText());
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButtonModifica;
	private javax.swing.JComboBox jComboBoxTipo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabelLand;
	private javax.swing.JLabel jLabelPrezzo;
	private javax.swing.JLabel jLabelTesto;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTextFieldLandArrivo;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldPrezzo;
	private javax.swing.JTextField jTextFieldTesto;
	// End of variables declaration//GEN-END:variables
	Componente componente;

	public void inizializzaComponenti() {
		this.setTitle(componente.getTile().getName());
		this.jTextFieldNome.setText(componente.getTile().getName());
		this.jComboBoxTipo.setSelectedIndex(componente.getType());
		if (this.componente.testo != null) {
			this.jTextFieldTesto.setText(this.componente.testo);
		}
		if (this.componente.landArrivo != null) {
			this.jTextFieldLandArrivo.setText(this.componente.landArrivo);
		}
		if (this.componente.prezzo != 0) {
			this.jTextFieldPrezzo.setText(String.valueOf(this.componente.prezzo));
		}
		// TODO
//        switch (this.componente.tipo){
//            case 2 : 
//                this.jLabelLand.setEnabled(true);
//                this.jButtonModifica.setEnabled(true);
//                break;
//            case 3 : 
//                this.jLabelTesto.setEnabled(true);
//                this.jTextFieldTesto.setEnabled(true);
//                break;
//            case 6 : 
//                this.jLabelPrezzo.setEnabled(true);
//                this.jTextFieldPrezzo.setEnabled(true);
//                break;
//            default :
//                break;
//        }
	}

	void centraFrameSuFrame(Window frame2) { // Posiziona il frame corrente al centro di frame2
		int x = frame2.getX();
		int y = frame2.getY();
		int larghezza = frame2.getWidth();
		int altezza = frame2.getHeight();
		this.setLocation((x + larghezza / 2) - this.getWidth() / 2, (y + altezza / 2) - this.getHeight() / 2);
	}
}
