package pokemon_online.world_builder;

import java.awt.Window;

import pokemon_online.land.Land;

public class Attributi extends javax.swing.JDialog {

	/** Creates new form Attributi */
	public Attributi(java.awt.Frame parent, boolean modal, Land land, Window formChiamante) {
		super(parent, modal);
		initComponents();
		this.landPrima = land;
		this.landDopo = land;
		this.inizializzaComponenti();
		this.centraFrameSuFrame(formChiamante);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldLarg = new javax.swing.JTextField();
		jTextFieldAlt = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldNome = new javax.swing.JTextField();
		jButtonOk = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Attributi");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setModal(true);
		setResizable(false);
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabel1.setText("Dimensioni:");

		jLabel2.setText("Larghezza:");

		jLabel3.setText("Altezza:");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup().add(jPanel1Layout
						.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout.createSequentialGroup().addContainerGap().add(jLabel1))
						.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
								.add(37, 37, 37)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
										.add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
										.add(jTextFieldLarg).add(jTextFieldAlt,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup().addContainerGap().add(jLabel1)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2)
								.add(jTextFieldLarg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel3)
								.add(jTextFieldAlt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabel4.setText("Nome:");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup().addContainerGap()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel2Layout.createSequentialGroup().add(10, 10, 10).add(jTextFieldNome,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
								.add(jLabel4))
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup().addContainerGap().add(jLabel4)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jTextFieldNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jButtonOk.setText("OK");
		jButtonOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOkActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup().addContainerGap()
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonOk))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout
				.createSequentialGroup().addContainerGap()
				.add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
				.add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jButtonOk)
				.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOkActionPerformed
		// TODO
//        this.landDopo = new Land(this.getNome(), this.getLarghezza(), this.getAltezza());
//        for (int c = 0; c < landDopo.getColsCount(); c++){//Per ogni colonna
//            if (c < landPrima.getColsCount()){
//                for (int r = 0; r < landDopo.getRowsCount(); r++){//Per ogni righa
//                    if (r < landPrima.getRowsCount())
//                        landDopo.componenti[c][r] = landPrima.componenti[c][r];
//                    else
//                        landDopo.componenti[c][r] = null;
//                }
//            }
//            else{
//                for (int r = 0; r < landDopo.getRowsCount(); r++){//Per ogni righa
//                    landDopo.componenti[c][r] = null;
//                }
//            }
//        }
//        this.dispose();
	}// GEN-LAST:event_jButtonOkActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonOk;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextFieldAlt;
	private javax.swing.JTextField jTextFieldLarg;
	private javax.swing.JTextField jTextFieldNome;
	// End of variables declaration//GEN-END:variables
	private Land landPrima;
	private Land landDopo;

	void inizializzaComponenti() {
		this.jTextFieldNome.setText(this.landPrima.getName());
		this.jTextFieldLarg.setText(String.valueOf(this.landPrima.getColsCount()));
		this.jTextFieldAlt.setText(String.valueOf(this.landPrima.getRowsCount()));
	}

	String getNome() {
		String nome = this.jTextFieldNome.getText();
		if (nome.isEmpty() == true)
			nome = "Senza nome";
		else if (nome.charAt(0) == ' ')
			nome = "Senza nome";
		return nome;
	}

	int getLarghezza() {
		int larghezza = Integer.parseInt(this.jTextFieldLarg.getText());
		if (larghezza < 1)
			larghezza = 1;
		return larghezza;
	}

	int getAltezza() {
		int altezza = Integer.parseInt(this.jTextFieldAlt.getText());
		if (altezza < 1)
			altezza = 1;
		return altezza;
	}

	Land getLand() {
		return landDopo;
	}

	void centraFrameSuFrame(Window frame2) { // Posiziona il frame corrente al centro di frame2
		int x = frame2.getX();
		int y = frame2.getY();
		int larghezza = frame2.getWidth();
		int altezza = frame2.getHeight();
		this.setLocation((x + larghezza / 2) - this.getWidth() / 2, (y + altezza / 2) - this.getHeight() / 2);
	}
}
