package pokemon_online.world_builder;
/*
 * LandBuilder2.java
 *
 * Created on 9 aprile 2007, 15.12
 */


import java.awt.Dimension;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.json.simple.parser.ParseException;

import pokemon_online.Configuration;
import pokemon_online.land.Land;
import pokemon_online.land.LandManager;

/**
 *
 * @author  Riccardo Cecchi
 * @since 04/11/21 (refactoring from a very old version)
 */
public class LandBuilder extends javax.swing.JFrame {
	
	// FIXME Move to its own project
	// FIXME Rename
    
    /** Creates new form LandBuilder2 */
    public LandBuilder() {
        initComponents();
        this.inizializzaElencoComponenti();
        this.centraFrame(this);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollBarVert = new javax.swing.JScrollBar();
        jScrollBarOriz = new javax.swing.JScrollBar();
        jPanelStrumenti = new javax.swing.JPanel();
        pannelloStrumentiTerreni = new PannelloStrumenti();
        jScrollBarTerreni = new javax.swing.JScrollBar();
        jScrollBarBlocchi = new javax.swing.JScrollBar();
        pannelloStrumentiBlocchi = new PannelloStrumenti();
        pannelloStrumentiPorte = new PannelloStrumenti();
        jScrollBarPorte = new javax.swing.JScrollBar();
        pannelloStrumentiCartelli = new PannelloStrumenti();
        jScrollBarCartelli = new javax.swing.JScrollBar();
        pannelloStrumentiErba = new PannelloStrumenti();
        jScrollBarErba = new javax.swing.JScrollBar();
        pannelloStrumentiBlocchiRim = new PannelloStrumenti();
        jScrollBarBlocchiRim = new javax.swing.JScrollBar();
        pannelloStrumentiCP = new PannelloStrumenti();
        jScrollBarCP = new javax.swing.JScrollBar();
        areaLavoroPannello = new AreaLavoro();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNuovo = new javax.swing.JMenuItem();
        jMenuItemApri = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItemSalva = new javax.swing.JMenuItem();
        jMenuItemSalvaNome = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCreaBordo = new javax.swing.JMenuItem();
        jMenuItemSposta = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuAggiornaStrumenti = new javax.swing.JMenuItem();
        jMenuLand = new javax.swing.JMenu();
        jMenuItemAttrib = new javax.swing.JMenuItem();
        jMenuItemMostri = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItemAnteprima = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Land Builder");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jScrollBarVert.setEnabled(false);
        jScrollBarVert.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarVertAdjustmentValueChanged(evt);
            }
        });

        jScrollBarOriz.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBarOriz.setEnabled(false);
        jScrollBarOriz.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarOrizAdjustmentValueChanged(evt);
            }
        });

        jPanelStrumenti.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pannelloStrumentiTerreni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiTerreni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiTerreniMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiTerreniLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiTerreni);
        pannelloStrumentiTerreni.setLayout(pannelloStrumentiTerreniLayout);
        pannelloStrumentiTerreniLayout.setHorizontalGroup(
            pannelloStrumentiTerreniLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiTerreniLayout.setVerticalGroup(
            pannelloStrumentiTerreniLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 64, Short.MAX_VALUE)
        );

        jScrollBarTerreni.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarTerreniAdjustmentValueChanged(evt);
            }
        });

        jScrollBarBlocchi.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarBlocchiAdjustmentValueChanged(evt);
            }
        });

        pannelloStrumentiBlocchi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiBlocchi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiBlocchiMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiBlocchiLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiBlocchi);
        pannelloStrumentiBlocchi.setLayout(pannelloStrumentiBlocchiLayout);
        pannelloStrumentiBlocchiLayout.setHorizontalGroup(
            pannelloStrumentiBlocchiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiBlocchiLayout.setVerticalGroup(
            pannelloStrumentiBlocchiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 180, Short.MAX_VALUE)
        );

        pannelloStrumentiPorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiPorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiPorteMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiPorteLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiPorte);
        pannelloStrumentiPorte.setLayout(pannelloStrumentiPorteLayout);
        pannelloStrumentiPorteLayout.setHorizontalGroup(
            pannelloStrumentiPorteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiPorteLayout.setVerticalGroup(
            pannelloStrumentiPorteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 32, Short.MAX_VALUE)
        );

        jScrollBarPorte.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarPorteAdjustmentValueChanged(evt);
            }
        });

        pannelloStrumentiCartelli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiCartelli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiCartelliMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiCartelliLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiCartelli);
        pannelloStrumentiCartelli.setLayout(pannelloStrumentiCartelliLayout);
        pannelloStrumentiCartelliLayout.setHorizontalGroup(
            pannelloStrumentiCartelliLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiCartelliLayout.setVerticalGroup(
            pannelloStrumentiCartelliLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 32, Short.MAX_VALUE)
        );

        jScrollBarCartelli.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarCartelliAdjustmentValueChanged(evt);
            }
        });

        pannelloStrumentiErba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiErba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiErbaMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiErbaLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiErba);
        pannelloStrumentiErba.setLayout(pannelloStrumentiErbaLayout);
        pannelloStrumentiErbaLayout.setHorizontalGroup(
            pannelloStrumentiErbaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiErbaLayout.setVerticalGroup(
            pannelloStrumentiErbaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 32, Short.MAX_VALUE)
        );

        jScrollBarErba.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarErbaAdjustmentValueChanged(evt);
            }
        });

        pannelloStrumentiBlocchiRim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiBlocchiRim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiBlocchiRimMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiBlocchiRimLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiBlocchiRim);
        pannelloStrumentiBlocchiRim.setLayout(pannelloStrumentiBlocchiRimLayout);
        pannelloStrumentiBlocchiRimLayout.setHorizontalGroup(
            pannelloStrumentiBlocchiRimLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiBlocchiRimLayout.setVerticalGroup(
            pannelloStrumentiBlocchiRimLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 32, Short.MAX_VALUE)
        );

        jScrollBarBlocchiRim.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarBlocchiRimAdjustmentValueChanged(evt);
            }
        });

        pannelloStrumentiCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pannelloStrumentiCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloStrumentiCPMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloStrumentiCPLayout = new org.jdesktop.layout.GroupLayout(pannelloStrumentiCP);
        pannelloStrumentiCP.setLayout(pannelloStrumentiCPLayout);
        pannelloStrumentiCPLayout.setHorizontalGroup(
            pannelloStrumentiCPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 128, Short.MAX_VALUE)
        );
        pannelloStrumentiCPLayout.setVerticalGroup(
            pannelloStrumentiCPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 32, Short.MAX_VALUE)
        );

        jScrollBarCP.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarCPAdjustmentValueChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelStrumentiLayout = new org.jdesktop.layout.GroupLayout(jPanelStrumenti);
        jPanelStrumenti.setLayout(jPanelStrumentiLayout);
        jPanelStrumentiLayout.setHorizontalGroup(
            jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelStrumentiLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiTerreni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jScrollBarTerreni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiBlocchi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jScrollBarBlocchi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiPorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollBarPorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiCartelli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollBarCartelli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiErba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollBarErba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelStrumentiLayout.createSequentialGroup()
                            .add(pannelloStrumentiBlocchiRim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollBarBlocchiRim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelStrumentiLayout.createSequentialGroup()
                        .add(pannelloStrumentiCP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollBarCP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStrumentiLayout.setVerticalGroup(
            jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelStrumentiLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollBarTerreni, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pannelloStrumentiTerreni, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarBlocchi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pannelloStrumentiBlocchi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarPorte, 0, 0, Short.MAX_VALUE)
                    .add(pannelloStrumentiPorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarCartelli, 0, 0, Short.MAX_VALUE)
                    .add(pannelloStrumentiCartelli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarErba, 0, 0, Short.MAX_VALUE)
                    .add(pannelloStrumentiErba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarBlocchiRim, 0, 0, Short.MAX_VALUE)
                    .add(pannelloStrumentiBlocchiRim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelStrumentiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollBarCP, 0, 0, Short.MAX_VALUE)
                    .add(pannelloStrumentiCP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        areaLavoroPannello.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaLavoroPannello.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaLavoroPannelloMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                areaLavoroPannelloMouseReleased(evt);
            }
        });
        areaLavoroPannello.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                areaLavoroPannelloMouseMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout areaLavoroPannelloLayout = new org.jdesktop.layout.GroupLayout(areaLavoroPannello);
        areaLavoroPannello.setLayout(areaLavoroPannelloLayout);
        areaLavoroPannelloLayout.setHorizontalGroup(
            areaLavoroPannelloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 399, Short.MAX_VALUE)
        );
        areaLavoroPannelloLayout.setVerticalGroup(
            areaLavoroPannelloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 476, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");
        jMenuItemNuovo.setText("Nuovo");
        jMenuItemNuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuovoActionPerformed(evt);
            }
        });

        jMenuFile.add(jMenuItemNuovo);

        jMenuItemApri.setText("Apri..");
        jMenuItemApri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApriActionPerformed(evt);
            }
        });

        jMenuFile.add(jMenuItemApri);

        jMenuFile.add(jSeparator2);

        jMenuItemSalva.setText("Salva");
        jMenuItemSalva.setEnabled(false);
        jMenuItemSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvaActionPerformed(evt);
            }
        });

        jMenuFile.add(jMenuItemSalva);

        jMenuItemSalvaNome.setText("Salva con nome...");
        jMenuItemSalvaNome.setEnabled(false);
        jMenuItemSalvaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvaNomeActionPerformed(evt);
            }
        });

        jMenuFile.add(jMenuItemSalvaNome);

        jMenuBar1.add(jMenuFile);

        jMenu1.setText("Strumenti");
        jMenuItemCreaBordo.setText("Crea bordo");
        jMenuItemCreaBordo.setEnabled(false);
        jMenuItemCreaBordo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreaBordoActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItemCreaBordo);

        jMenuItemSposta.setText("Sposta land");
        jMenuItemSposta.setEnabled(false);
        jMenuItemSposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSpostaActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItemSposta);

        jMenu1.add(jSeparator3);

        jMenuAggiornaStrumenti.setText("Aggiorna pannello strumenti");
        jMenuAggiornaStrumenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAggiornaStrumentiActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuAggiornaStrumenti);

        jMenuBar1.add(jMenu1);

        jMenuLand.setText("Land");
        jMenuItemAttrib.setText("Attributi...");
        jMenuItemAttrib.setEnabled(false);
        jMenuItemAttrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAttribActionPerformed(evt);
            }
        });

        jMenuLand.add(jMenuItemAttrib);

        jMenuItemMostri.setText("Mostri");
        jMenuItemMostri.setEnabled(false);
        jMenuLand.add(jMenuItemMostri);

        jMenuLand.add(jSeparator1);

        jMenuItemAnteprima.setText("Anteprima");
        jMenuItemAnteprima.setEnabled(false);
        jMenuItemAnteprima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnteprimaActionPerformed(evt);
            }
        });

        jMenuLand.add(jMenuItemAnteprima);

        jMenuBar1.add(jMenuLand);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelStrumenti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollBarOriz, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(areaLavoroPannello, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollBarVert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, areaLavoroPannello, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollBarVert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelStrumenti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollBarOriz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollBarCPAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarCPAdjustmentValueChanged
        this.pannelloStrumentiCP.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarCPAdjustmentValueChanged

    private void pannelloStrumentiCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiCPMouseClicked
        if (checkPoint[0] != null){
            this.pannelloStrumentiCP.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiCP.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiCP.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiCP.getComponenteSelezionato());
        }
        repaint(); 
    }//GEN-LAST:event_pannelloStrumentiCPMouseClicked

    private void jMenuItemSpostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSpostaActionPerformed
            Sposta sposta = new Sposta(new javax.swing.JFrame(), true, this.land, this);
            this.land = sposta.landPrima;
            this.areaLavoroPannello.setLand(this.land);
            repaint();
    }//GEN-LAST:event_jMenuItemSpostaActionPerformed

    private void jMenuItemSalvaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvaNomeActionPerformed
        JFileChooser salva = new JFileChooser("land/");
        
        int risposta = salva.showSaveDialog(this);
        if(risposta==JFileChooser.APPROVE_OPTION)
            this.salva(salva.getSelectedFile().getPath() + ".lnd");
    repaint();
    }//GEN-LAST:event_jMenuItemSalvaNomeActionPerformed

    private void jMenuAggiornaStrumentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAggiornaStrumentiActionPerformed
        this.inizializzaElencoComponenti();
        repaint();
    }//GEN-LAST:event_jMenuAggiornaStrumentiActionPerformed

    private void jMenuItemApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApriActionPerformed
        JFileChooser apri = new JFileChooser("land/");
        apri.setFileSelectionMode(JFileChooser.FILES_ONLY);
        apri.setMultiSelectionEnabled(false);
        
        int risposta = apri.showOpenDialog(this);
        if(risposta==JFileChooser.APPROVE_OPTION) {
        	land = carica(apri.getSelectedFile());
            this.land.inizializzaImmaginiComponenti();
            this.inizializzaBuilder();
        }
        repaint();
    }//GEN-LAST:event_jMenuItemApriActionPerformed

    private void jMenuItemSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvaActionPerformed
        if (this.saved == null){
            JFileChooser salva = new JFileChooser("land/");
        
            int risposta = salva.showSaveDialog(this);
            if(risposta==JFileChooser.APPROVE_OPTION) 
                this.salva(salva.getSelectedFile().getPath() + ".lnd");
        }
        else {
            this.salva(saved);
        }
    }//GEN-LAST:event_jMenuItemSalvaActionPerformed

    private void jScrollBarBlocchiRimAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarBlocchiRimAdjustmentValueChanged
        this.pannelloStrumentiBlocchiRim.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarBlocchiRimAdjustmentValueChanged

    private void pannelloStrumentiBlocchiRimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiBlocchiRimMouseClicked
        if (blocchiRim[0] != null){
            this.pannelloStrumentiBlocchiRim.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiBlocchiRim.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiBlocchiRim.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiBlocchiRim.getComponenteSelezionato());
        }
        repaint();  
    }//GEN-LAST:event_pannelloStrumentiBlocchiRimMouseClicked

    private void jScrollBarErbaAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarErbaAdjustmentValueChanged
        this.pannelloStrumentiErba.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarErbaAdjustmentValueChanged

    private void pannelloStrumentiErbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiErbaMouseClicked
        if (erba[0] != null){
            this.pannelloStrumentiErba.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiErba.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiErba.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiErba.getComponenteSelezionato());
        }
        repaint(); 
    }//GEN-LAST:event_pannelloStrumentiErbaMouseClicked

    private void jScrollBarCartelliAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarCartelliAdjustmentValueChanged
        this.pannelloStrumentiCartelli.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarCartelliAdjustmentValueChanged

    private void pannelloStrumentiCartelliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiCartelliMouseClicked
        if (cartelli[0] != null){
            this.pannelloStrumentiCartelli.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiCartelli.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiCartelli.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiCartelli.getComponenteSelezionato());
        }
        repaint();  
    }//GEN-LAST:event_pannelloStrumentiCartelliMouseClicked

    private void jScrollBarPorteAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarPorteAdjustmentValueChanged
        this.pannelloStrumentiPorte.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarPorteAdjustmentValueChanged

    private void pannelloStrumentiPorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiPorteMouseClicked
        if (porte[0] != null){
            this.pannelloStrumentiPorte.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiPorte.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiPorte.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiPorte.getComponenteSelezionato());
        }
        repaint();    
    }//GEN-LAST:event_pannelloStrumentiPorteMouseClicked

    private void jScrollBarBlocchiAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarBlocchiAdjustmentValueChanged
        this.pannelloStrumentiBlocchi.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarBlocchiAdjustmentValueChanged

    private void pannelloStrumentiBlocchiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiBlocchiMouseClicked
        if (blocchi[0] != null){
            this.pannelloStrumentiBlocchi.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiBlocchi.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiBlocchi.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiBlocchi.getComponenteSelezionato());
        }
        repaint();     
    }//GEN-LAST:event_pannelloStrumentiBlocchiMouseClicked

    private void jScrollBarTerreniAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarTerreniAdjustmentValueChanged
        this.pannelloStrumentiTerreni.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarTerreniAdjustmentValueChanged

    private void pannelloStrumentiTerreniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloStrumentiTerreniMouseClicked
        if (terreni[0] != null){this.pannelloStrumentiTerreni.setXMouse(this.setClick(evt.getX()));
            this.pannelloStrumentiTerreni.setYMouse(this.setClick(evt.getY() + this.pannelloStrumentiTerreni.getYScroll()));

            this.areaLavoroPannello.setComponenteInUso(this.pannelloStrumentiTerreni.getComponenteSelezionato());
        }
        repaint();
    }//GEN-LAST:event_pannelloStrumentiTerreniMouseClicked

    private void jMenuItemAttribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAttribActionPerformed
            Attributi attributi = new Attributi(new javax.swing.JFrame(), true, this.land, this);
            this.land = attributi.getLand();
            this.areaLavoroPannello.setLand(land);
            this.setTitle(land.getName());
            
            this.settaBarreScorrimento();
            
            repaint();
    }//GEN-LAST:event_jMenuItemAttribActionPerformed

    private void jMenuItemCreaBordoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreaBordoActionPerformed
            CreaBordo creaBordo = new CreaBordo(new javax.swing.JFrame(), true, this.land, this.blocchi, this);
            this.land = creaBordo.getLand();
            this.areaLavoroPannello.setLand(land);
            
            this.settaBarreScorrimento();
            repaint();
    }//GEN-LAST:event_jMenuItemCreaBordoActionPerformed

    private void areaLavoroPannelloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaLavoroPannelloMouseClicked
        this.colonnaClick = this.setClick(evt.getX() + this.areaLavoroPannello.getXScroll());
        this.rigaClick = this.setClick(evt.getY() + this.areaLavoroPannello.getYScroll());
        //this.jLabel1.setText(String.valueOf(colonnaClick) + ", " + String.valueOf(rigaClick));
        
        if (this.land != null){
            if ((this.colonnaClick < this.land.getColsCount())&&(this.rigaClick < this.land.getRowsCount())){ //Se è stato fatto click in un punto interno alla land
                if (evt.getButton() == 1){ //Se è stato fatto click col tasto sx
                    if (this.areaLavoroPannello.getComponenteInUso()!= null){
                        this.land.componenti[colonnaClick][rigaClick] = new Componente(this.areaLavoroPannello.getComponenteInUso());
                        switch (this.land.componenti[colonnaClick][rigaClick].tipo){
                            case 2 : 
                                SetPorta setPorta = new SetPorta(new javax.swing.JFrame(), true, this.land.componenti[colonnaClick][rigaClick], this);
                                break;
                            case 3 : 
                                this.land.componenti[colonnaClick][rigaClick].testo = JOptionPane.showInputDialog(null, "Immettere il testo del cartello", "Testo del cartello", JOptionPane.PLAIN_MESSAGE);
                                break;
                            case 6 : 
                                this.land.componenti[colonnaClick][rigaClick].prezzo = Integer.parseInt(JOptionPane.showInputDialog(null, "Immettere il prezzo di uso del Check Point", "Prezzo del Check Point", JOptionPane.PLAIN_MESSAGE));
                                break;
                        }
                    } else {
                        this.areaLavoroPannello.setComponenteInUso(this.land.componenti[colonnaClick][rigaClick]);
                        this.land.componenti[colonnaClick][rigaClick] = null;
                    }
                    this.areaLavoroPannello.setLand(this.land);
                }
                else //Se non è stato fatto click col tasto sx
                    if (evt.getButton() == 3) //Se è stato fatto click col tasto dx
                        if (this.land.componenti[colonnaClick][rigaClick] != null){
                            this.areaLavoroPannello.setComponenteInUso(null);
                            new AttributiComponente(new javax.swing.JFrame(), true, this.land.componenti[colonnaClick][rigaClick], this);
                            this.areaLavoroPannello.setLand(this.land);
                        }
            }else//Se è stato fatto click in un punto esterno alla land
                if (evt.getButton() == 1)
                    this.areaLavoroPannello.setComponenteInUso(null);
        }
        repaint();
    }//GEN-LAST:event_areaLavoroPannelloMouseClicked

    private void areaLavoroPannelloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaLavoroPannelloMouseReleased
        this.areaLavoroPannello.setXMouse(evt.getX());
        this.areaLavoroPannello.setYMouse(evt.getY());
        repaint();
    }//GEN-LAST:event_areaLavoroPannelloMouseReleased

    private void areaLavoroPannelloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaLavoroPannelloMouseMoved
        this.areaLavoroPannello.setXMouse(evt.getX());
        this.areaLavoroPannello.setYMouse(evt.getY());
        repaint();
    }//GEN-LAST:event_areaLavoroPannelloMouseMoved

    private void jScrollBarOrizAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarOrizAdjustmentValueChanged
        this.areaLavoroPannello.setXScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarOrizAdjustmentValueChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.land != null){
            this.settaBarreScorrimento();
        }
        repaint();
    }//GEN-LAST:event_formComponentResized

    private void jScrollBarVertAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarVertAdjustmentValueChanged
        this.areaLavoroPannello.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarVertAdjustmentValueChanged

    private void jMenuItemAnteprimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnteprimaActionPerformed
        AnteprimaLand ant = new AnteprimaLand(new javax.swing.JFrame(), true,this.land, this);
    }//GEN-LAST:event_jMenuItemAnteprimaActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        //this.jLabel1.setText(String.valueOf(evt.getKeyCode()));
        int codiceTasto = evt.getKeyCode();
        if((codiceTasto == 127)||(codiceTasto == 27)){
            this.areaLavoroPannello.setComponenteInUso(null);
        }
        repaint();
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItemNuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuovoActionPerformed
        Nuovo nuovo = new Nuovo(new javax.swing.JFrame(), true, this.land, this);
        
        this.land = nuovo.getLand();
        
        if (nuovo.getRisposta() == true) {
            this.inizializzaBuilder();
            
            this.saved = null;
            
        }
        
        repaint();
    }//GEN-LAST:event_jMenuItemNuovoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandBuilder().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AreaLavoro areaLavoroPannello;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAggiornaStrumenti;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAnteprima;
    private javax.swing.JMenuItem jMenuItemApri;
    private javax.swing.JMenuItem jMenuItemAttrib;
    private javax.swing.JMenuItem jMenuItemCreaBordo;
    private javax.swing.JMenuItem jMenuItemMostri;
    private javax.swing.JMenuItem jMenuItemNuovo;
    private javax.swing.JMenuItem jMenuItemSalva;
    private javax.swing.JMenuItem jMenuItemSalvaNome;
    private javax.swing.JMenuItem jMenuItemSposta;
    private javax.swing.JMenu jMenuLand;
    private javax.swing.JPanel jPanelStrumenti;
    private javax.swing.JScrollBar jScrollBarBlocchi;
    private javax.swing.JScrollBar jScrollBarBlocchiRim;
    private javax.swing.JScrollBar jScrollBarCP;
    private javax.swing.JScrollBar jScrollBarCartelli;
    private javax.swing.JScrollBar jScrollBarErba;
    private javax.swing.JScrollBar jScrollBarOriz;
    private javax.swing.JScrollBar jScrollBarPorte;
    private javax.swing.JScrollBar jScrollBarTerreni;
    private javax.swing.JScrollBar jScrollBarVert;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private PannelloStrumenti pannelloStrumentiBlocchi;
    private PannelloStrumenti pannelloStrumentiBlocchiRim;
    private PannelloStrumenti pannelloStrumentiCP;
    private PannelloStrumenti pannelloStrumentiCartelli;
    private PannelloStrumenti pannelloStrumentiErba;
    private PannelloStrumenti pannelloStrumentiPorte;
    private PannelloStrumenti pannelloStrumentiTerreni;
    // End of variables declaration//GEN-END:variables
    Land land = null;
    int colonnaClick;
    int rigaClick;
    
    String saved = null;
    
    Toolkit kit = Toolkit.getDefaultToolkit();
    
    String[] elencoFile;
    
    Componente[] componentiTot;
    Componente[] terreni;
    Componente[] blocchi;
    Componente[] porte;
    Componente[] cartelli;
    Componente[] erba;
    Componente[] blocchiRim;
    Componente[] checkPoint;
    
    int setClick(int coordinata){
        //CICLO
        int trovato = 0;
        while (trovato == 0) {
            if (coordinata % 32 == 0) //Se la coordinata è un multiplo di 32
                trovato = 1;
        else //Se la coordinata non è un multiplo di 32
            coordinata--;
        }
        return coordinata/32;
    }
    
    public void inizializzaElencoComponenti (){
        
        MediaTracker track = new MediaTracker(this);
        File compsDir = new File(Configuration.RESOURCES_DIR, "componenti/");
        elencoFile = compsDir.list(); //Creo una lista dei file nella dir componenti
        
        this.componentiTot = new Componente[this.elencoFile.length];
        
        this.terreni = new Componente[this.elencoFile.length];
        this.blocchi = new Componente[this.elencoFile.length];
        this.porte = new Componente[this.elencoFile.length];
        this.cartelli = new Componente[this.elencoFile.length];
        this.erba = new Componente[this.elencoFile.length];
        this.blocchiRim = new Componente[this.elencoFile.length];
        this.checkPoint = new Componente[this.elencoFile.length];
        
        for (int i = 0; i < elencoFile.length; i++){
            try{ //Carico i componenti e li memorizzo nell'array componentiTot'
            	// FIXME
                FileInputStream fileIn = new FileInputStream(new File(compsDir, this.elencoFile[i]));
                ObjectInputStream objectIn = new ObjectInputStream(fileIn);
                componentiTot[i] = (Componente)objectIn.readObject();
                objectIn.close(); //Chiudo il flusso
            }catch(IOException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Errore nel caricare il componente1: " + e.toString());
            }catch(ClassNotFoundException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Errore nel caricare il componente: " + e.toString());
            }
        }
        
        //javax.swing.JOptionPane.showMessageDialog(null, "Componenti caricati con successo");
        
        for (int i = 0; i < componentiTot.length ; i++){
            //Inizializzo la variabile immagine di ogni componente
            this.componentiTot[i].immagine = null;
            this.componentiTot[i].immagine = kit.getImage("immagini/componenti/" + componentiTot[i].nome + ".gif");
            track.addImage(componentiTot[i].immagine, i);
        }
        try {
            track.waitForAll();
        } catch (InterruptedException e){}
        
        //javax.swing.JOptionPane.showMessageDialog(null, "Immagini caricate con successo");
        
        int indexTerreni = 0;
        int indexBlocchi = 0;
        int indexPorte = 0;
        int indexCartelli = 0;
        int indexErba = 0;
        int indexBlocchiRim = 0;
        int indexCheckPoint = 0;
        
        for (int i = 0; i < componentiTot.length ; i++){
            //Ordino i componenti nei rispettivi array a seconda del tipo
            
                switch (componentiTot[i].tipo){
                    case 0 : 
                        this.terreni[indexTerreni] = componentiTot[i];
                        indexTerreni++;
                        break;
                    case 1 : 
                        this.blocchi[indexBlocchi] = componentiTot[i];
                        indexBlocchi++;
                        break;
                    case 2 : 
                        this.porte[indexPorte] = componentiTot[i];
                        indexPorte++;
                        break;
                    case 3 : 
                        this.cartelli[indexCartelli] = componentiTot[i];
                        indexCartelli++;
                        break;
                    case 4 : 
                        this.erba[indexErba] = componentiTot[i];
                        indexErba++;
                        break;
                    case 5 : 
                        this.blocchiRim[indexBlocchiRim] = componentiTot[i];
                        indexBlocchiRim++;
                        break;
                    case 6 :
                        this.checkPoint[indexCheckPoint] = componentiTot[i];
                        indexCheckPoint++;
                        break;
                }
        }
        
        //Inizializzo i blocchi a scorrimento  
        int index = 0;
        boolean fineArray = false;
        while (fineArray == false){
            if (this.terreni[index] == null)
                fineArray = true;
            else
                index++;
        }
        
        if (terreni[0] != null){
            this.pannelloStrumentiTerreni.setComponenti(terreni);
            this.jScrollBarTerreni.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.blocchi[index] == null)
                fineArray = true;
            else
                index++;
        }
        
        if (blocchi[0] != null){
            this.pannelloStrumentiBlocchi.setComponenti(blocchi);
            this.jScrollBarBlocchi.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.porte[index] == null)
                fineArray = true;
            else
                index++;
        }
        
        if (porte[0] != null){
            this.pannelloStrumentiPorte.setComponenti(porte);
            this.jScrollBarPorte.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.cartelli[index] == null)
                fineArray = true;
            else
                index++;
        }
        
        if (cartelli[0] != null){
            this.pannelloStrumentiCartelli.setComponenti(cartelli);
            this.jScrollBarCartelli.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.erba[index] == null)
                fineArray = true;
            else
                index++;
        }
        
        if (erba[0] != null){
            this.pannelloStrumentiErba.setComponenti(erba);
            this.jScrollBarErba.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.blocchiRim[index] == null)
                fineArray = true;
            else
                index++;
        } 
        
        if (blocchiRim[0] != null){
            this.pannelloStrumentiBlocchiRim.setComponenti(blocchiRim);
            this.jScrollBarBlocchiRim.setMaximum((index / 4) * 32);
        }
        
        index = 0;
        fineArray = false;
        while (fineArray == false){
            if (this.checkPoint[index] == null)
                fineArray = true;
            else
                index++;
        } 
        
        if (checkPoint[0] != null){
            this.pannelloStrumentiCP.setComponenti(checkPoint);
            this.jScrollBarCP.setMaximum((index / 4) * 32);
        }
    }
    
    public static void centraFrame(Window frame) {
        Dimension frameSize = frame.getSize();
        frame.setSize(frameSize);
        frame.setLocation(
            (Toolkit.getDefaultToolkit().getScreenSize().width
                - frameSize.width) / 2,
            (Toolkit.getDefaultToolkit().getScreenSize().height
                - frameSize.height) / 2);
    }
    
    void settaBarreScorrimento(){
            //Setto la barra a scorrimento orizzontale
            if (this.land.getColsCount() * 32 > this.areaLavoroPannello.getWidth()){
                this.jScrollBarOriz.setEnabled(true);
                this.jScrollBarOriz.setMaximum((this.land.getColsCount() * 32 - this.areaLavoroPannello.getWidth()) + 32);
            }
            else{
                this.jScrollBarOriz.setEnabled(false);
                this.areaLavoroPannello.setXScroll(0);
            }

            //Setto la barra a scorrimento verticale
            if (this.land.getRowsCount() * 32 > this.areaLavoroPannello.getHeight()){
                this.jScrollBarVert.setEnabled(true);
                this.jScrollBarVert.setMaximum((this.land.getRowsCount() * 32 - this.areaLavoroPannello.getHeight()) + 32);
            }
            else{
                this.jScrollBarVert.setEnabled(false);
                this.areaLavoroPannello.setYScroll(0);
            }
    }
    
    void salva(String nomeFile){
        try{
            FileOutputStream fileOut = new FileOutputStream(nomeFile); //Creo un flusso di output verso l'oggetto nomecomponente.txr nella cartella componenti'
            this.saved = nomeFile;
            ObjectOutputStream objectOut = new ObjectOutputStream(fileOut);
            objectOut.writeObject(this.land); //Scrivo il componente nel flusso
            objectOut.close(); //Chiudo il flusso
            //javax.swing.JOptionPane.showMessageDialog(null, "Land creato con successo");
        }catch(IOException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Errore nel creare la land: " + e.toString());
        }
    }
    
    private Land carica(File file){
    	try {
			return LandManager.getMgr().loadLand(file);
		} catch (IOException | ParseException e) {
			JOptionPane.showMessageDialog(this, e.toString() , "Land loading error", JOptionPane.ERROR_MESSAGE);
		}
		return null;
    }
    
    void inizializzaBuilder(){
            this.setTitle(land.getName() + " - Land Builder");
            this.areaLavoroPannello.setLand(this.land);
        
            this.jMenuItemAnteprima.setEnabled(true);
            this.jMenuItemMostri.setEnabled(true);
            this.jMenuItemCreaBordo.setEnabled(true);
            this.jMenuItemAttrib.setEnabled(true);
            this.jMenuItemSposta.setEnabled(true);
            this.jMenuItemSalva.setEnabled(true);
            this.jMenuItemSalvaNome.setEnabled(true);
        
            this.areaLavoroPannello.setYScroll(0);
            this.areaLavoroPannello.setXScroll(0);
        
            this.settaBarreScorrimento();
    }
}
