package pokemon_online.world_builder;


import java.awt.Window;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;

import pokemon_online.land.Land;

public class SetPorta extends javax.swing.JDialog {
    
    /** Creates new form SetPorta */
    public SetPorta(java.awt.Frame parent, boolean modal, Componente componente, Window formChiamante) {
        super(parent, modal);
        initComponents();
        this.componente = componente;
        this.centraFrameSuFrame(formChiamante);
        this.inizializzaComponenti();
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jComboBoxLand = new javax.swing.JComboBox();
        pannelloAnteprimaLand = new PannelloAnteprimaLand();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldColonna = new javax.swing.JTextField();
        jTextFieldRiga = new javax.swing.JTextField();
        jScrollBarVert = new javax.swing.JScrollBar();
        jScrollBarOriz = new javax.swing.JScrollBar();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxLand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DESTINAZIONE" }));
        jComboBoxLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLandActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jComboBoxLand, 0, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jComboBoxLand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pannelloAnteprimaLand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pannelloAnteprimaLand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pannelloAnteprimaLandMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pannelloAnteprimaLandLayout = new org.jdesktop.layout.GroupLayout(pannelloAnteprimaLand);
        pannelloAnteprimaLand.setLayout(pannelloAnteprimaLandLayout);
        pannelloAnteprimaLandLayout.setHorizontalGroup(
            pannelloAnteprimaLandLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 266, Short.MAX_VALUE)
        );
        pannelloAnteprimaLandLayout.setVerticalGroup(
            pannelloAnteprimaLandLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 172, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldColonna.setEditable(false);
        jTextFieldColonna.setText("0");

        jTextFieldRiga.setEditable(false);
        jTextFieldRiga.setText("0");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jTextFieldColonna, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldRiga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldRiga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldColonna, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollBarVert.setEnabled(false);
        jScrollBarVert.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarVertAdjustmentValueChanged(evt);
            }
        });

        jScrollBarOriz.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBarOriz.setEnabled(false);
        jScrollBarOriz.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBarOrizAdjustmentValueChanged(evt);
            }
        });

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(pannelloAnteprimaLand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollBarVert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonOk))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jScrollBarOriz, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .add(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollBarVert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .add(pannelloAnteprimaLand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollBarOriz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonOk)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
            this.componente.landArrivo = this.getNomeLandArrivo();
            this.componente.colonnaArrivo = Integer.parseInt(this.jTextFieldColonna.getText());
            this.componente.righaArrivo = Integer.parseInt(this.jTextFieldRiga.getText());
        this.dispose();
        repaint();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jScrollBarOrizAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarOrizAdjustmentValueChanged
        this.pannelloAnteprimaLand.setXScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarOrizAdjustmentValueChanged

    private void jScrollBarVertAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarVertAdjustmentValueChanged
        this.pannelloAnteprimaLand.setYScroll(evt.getValue());
        repaint();
    }//GEN-LAST:event_jScrollBarVertAdjustmentValueChanged

    private void pannelloAnteprimaLandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloAnteprimaLandMouseClicked
        if (evt.getButton() == 1){ //Se è stato fatto click col tasto sx
            if (this.jComboBoxLand.getSelectedIndex() != 0){
                int colonna = this.setClick(evt.getX() + this.pannelloAnteprimaLand.getXScroll());
                int riga = this.setClick(evt.getY() + this.pannelloAnteprimaLand.getYScroll());
                if ((colonna < this.land[this.jComboBoxLand.getSelectedIndex() - 1].getColsCount())&&(riga < this.land[this.jComboBoxLand.getSelectedIndex() - 1].getRowsCount())){
                        this.jTextFieldColonna.setText(String.valueOf(colonna));
                        this.jTextFieldRiga.setText(String.valueOf(riga));
                }
            }  
        }
        repaint();
    }//GEN-LAST:event_pannelloAnteprimaLandMouseClicked

    private void jComboBoxLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLandActionPerformed
      
        if (this.jComboBoxLand.getSelectedIndex() != 0){
            this.settaBarreScorrimento(this.land[this.jComboBoxLand.getSelectedIndex() - 1]);
            this.pannelloAnteprimaLand.setLand(this.land[this.jComboBoxLand.getSelectedIndex() - 1]);
        }
        else{
            this.jScrollBarOriz.setEnabled(false);
            this.jScrollBarVert.setEnabled(false);
            this.pannelloAnteprimaLand.setLand(null);
        }
        repaint();
    }//GEN-LAST:event_jComboBoxLandActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxLand;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBarOriz;
    private javax.swing.JScrollBar jScrollBarVert;
    private javax.swing.JTextField jTextFieldColonna;
    private javax.swing.JTextField jTextFieldRiga;
    private PannelloAnteprimaLand pannelloAnteprimaLand;
    // End of variables declaration//GEN-END:variables
    Componente componente;
    Land[] land;
    
    String[] elencoFile;
    
    void inizializzaComponenti(){
        
        this.setTitle(componente.nome + " - Set Land destinazione");
        
        elencoFile = new File("land/").list(); //Creo una lista dei file nella dir componenti
        
        /*for (int i = 0; i < elencoFile.length; i++){
            System.out.println(elencoFile[i]);
        }*/
        
        this.land = new Land[elencoFile.length];
        
        for (int i = 0; i < elencoFile.length; i++){
            try{ //Carico i componenti e li memorizzo nell'array land
                FileInputStream fileIn = new FileInputStream("land/" +  this.elencoFile[i]);
                ObjectInputStream objectIn = new ObjectInputStream(fileIn);
                land[i] = (Land)objectIn.readObject();
                objectIn.close(); //Chiudo il flusso
            }catch(IOException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Errore nel caricare la Land: " + e.toString());
            }catch(ClassNotFoundException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Errore nel caricare la Land: " + e.toString());
            }
        }
        
        for (int i = 0; i < elencoFile.length ; i++){
            //Inizializzo la variabile immagine di ogni land
            this.land[i].inizializzaImmaginiComponenti();
            this.jComboBoxLand.addItem(this.land[i].getName());
        }
        
        this.jTextFieldColonna.setText(String.valueOf(this.componente.colonnaArrivo));
        this.jTextFieldRiga.setText(String.valueOf(this.componente.righaArrivo));
        
        if (this.componente.landArrivo != null){//Se il componente ha già settata una land d'arrivo, setta il menù a tendina su quella land
            boolean trovato = false;
            int i = 0;
            while ((trovato == false)&&(i < this.land.length)){
                if (this.componente.landArrivo.equals(this.land[i].getName()) == true){
                    trovato = true;
                    this.jComboBoxLand.setSelectedIndex(i + 1);
                    this.settaBarreScorrimento(this.land[this.jComboBoxLand.getSelectedIndex() - 1]);
                    this.pannelloAnteprimaLand.setLand(this.land[this.jComboBoxLand.getSelectedIndex() - 1]);
                }
                else
                    i++;
            }
        }
    }
    
    void centraFrameSuFrame(Window frame2) { //Posiziona il frame corrente al centro di frame2
        int x = frame2.getX();
        int y = frame2.getY();
        int larghezza = frame2.getWidth();
        int altezza = frame2.getHeight();
        this.setLocation((x + larghezza / 2) - this.getWidth()/2, (y + altezza / 2) - this.getHeight() / 2);
    }
    
    void settaBarreScorrimento(Land land){
        this.pannelloAnteprimaLand.setXScroll(0);
        this.pannelloAnteprimaLand.setYScroll(0);
        this.jScrollBarOriz.setValue(0);
        this.jScrollBarVert.setValue(0);
            //Setto la barra a scorrimento orizzontale
            if (land.getColsCount() * 16 > this.pannelloAnteprimaLand.getWidth()){
                this.jScrollBarOriz.setEnabled(true);
                this.jScrollBarOriz.setMaximum((land.getColsCount() * 16 - this.pannelloAnteprimaLand.getWidth()) + 16);
            }
            else 
                this.jScrollBarOriz.setEnabled(false);
            //Setto la barra a scorrimento verticale
            if (land.getRowsCount() * 16 > this.pannelloAnteprimaLand.getHeight()){
                this.jScrollBarVert.setEnabled(true);
                this.jScrollBarVert.setMaximum((land.getRowsCount() * 16 - this.pannelloAnteprimaLand.getHeight()) + 16);
            }
            else
                this.jScrollBarVert.setEnabled(false);
    }
    
    int setClick(int coordinata){
        //CICLO
        int trovato = 0;
        while (trovato == 0) {
            if (coordinata % 16 == 0) //Se la coordinata è un multiplo di 32
                trovato = 1;
        else //Se la coordinata non è un multiplo di 32
            coordinata--;
        }
        return coordinata/16;
    }
    
    String getNomeLandArrivo(){
        String nome;
        if (this.jComboBoxLand.getSelectedIndex() != 0)
            nome = this.land[this.jComboBoxLand.getSelectedIndex() - 1].getName();
        else
            nome = null;
        return nome;
    }
}
